### ISSUE TITLE
Function name must start with a capital of "s:"

### ISSUE THREAD

**Issue by gmoshkin** [rhysd/vim-textobj-clang#4]
When opening a `cpp` file I get these error messages:
![image](https://cloud.githubusercontent.com/assets/10168363/20721699/d6daae96-b674-11e6-9872-2da38239cb38.png)

**Comment by rhysd** [comment]
It's not vim-textobj-clang, but vim-textobj-function-clang. You should make an issue there. https://github.com/libclang-vim/vim-textobj-function-clang

**Comment by rhysd** [comment]
@gmoshkin I fixed this in https://github.com/libclang-vim/vim-textobj-function-clang/commit/2416631442964178c25d716dfdc3f2c69cad17b4 . Please try it before creating issue.
